apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
          app: my-app
  strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
        type: RollingUpdate
  template:
        metadata:
          labels:
            app: my-app
        spec:
          containers:
            - image: demoapi:latest
              imagePullPolicy: Never
              name: demoapi
              ports:
                - containerPort: 8080
          hostAliases:
          #- ip: "172.17.0.1"
          - ip: "192.168.49.1"
            hostnames:
            - postgres.local